sonar.projectKey=Marcurio22_TFG-Marcos-Zamorano
sonar.organization=marcurio22

sonar.sources=webapp/trazasytrazadas
sonar.python.version=3.13

sonar.exclusions=\
  tests/**,\
  **/tests/**,\
  webapp/tests/**,\
  tests/selenium/**,\
  **/selenium/**,\
  prototipos/**,\
  **/prototipos/**,\
  webapp/prototipos/**,\
  webapp/trazasytrazadas/prototipos/**,\
  **/migrations/**,\
  **/__pycache__/**,\
  **/venv/**,\
  **/env/**,\
  **/.venv/**,\
  **/node_modules/**,\
  **/media/**,\
  **/*.pyc

sonar.coverage.exclusions=\
  tests/**,\
  **/tests/**,\
  webapp/tests/**,\
  tests/selenium/**,\
  **/selenium/**,\
  prototipos/**,\
  **/prototipos/**,\
  webapp/prototipos/**,\
  webapp/trazasytrazadas/prototipos/**,\
  **/migrations/**,\
  **/__pycache__/**,\
  **/venv/**,\
  **/env/**,\
  **/.venv/**,\
  **/node_modules/**,\
  **/media/**,\
  **/*.html,\
  **/*.css,\
  **/*.js,\
  **/*.pyc

sonar.cpd.exclusions=\
  tests/**,\
  **/tests/**,\
  webapp/tests/**,\
  tests/selenium/**,\
  **/selenium/**,\
  prototipos/**,\
  **/prototipos/**,\
  webapp/prototipos/**,\
  webapp/trazasytrazadas/prototipos/**

sonar.python.coverage.reportPaths=coverage.xml