sonar.projectKey=Marcurio22_TFG-Marcos-Zamorano
sonar.organization=marcurio22

sonar.sources=webapp
sonar.python.version=3.13

sonar.exclusions=webapp/prototipos/**,**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/node_modules/**,**/static/**,**/media/**,**/*.html,**/*.css,**/*.js

sonar.tests=webapp/tests
sonar.test.inclusions=**/tests/**,**/test_*.py,**/*_test.py

sonar.coverage.exclusions=webapp/prototipos/**,**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/node_modules/**,**/static/**,**/media/**,**/*.html,**/*.css,**/*.js

sonar.coverage.python.coverage.reportPaths=coverage.xml