sonar.projectKey=Marcurio22_TFG-Marcos-Zamorano
sonar.organization=marcurio22

sonar.sources=webapp/trazasytrazadas
sonar.python.version=3.13

sonar.exclusions=\
  webapp/tests/**,\
  tests/**,\
  webapp/prototipos/**,\
  prototipos/**,\
  **/migrations/**,\
  **/__pycache__/**,\
  **/venv/**,\
  **/env/**,\
  **/node_modules/**,\
  **/media/**,\
  **/*.pyc

sonar.coverage.exclusions=\
  webapp/tests/**,\
  tests/**,\
  webapp/prototipos/**,\
  prototipos/**,\
  **/migrations/**,\
  **/__pycache__/**,\
  **/venv/**,\
  **/env/**,\
  **/node_modules/**,\
  **/media/**,\
  **/*.html,\
  **/*.css,\
  **/*.js

sonar.python.coverage.reportPaths=coverage.xml